---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads-pv 
spec:
  capacity:
    storage: 460Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/hd/transmission/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: transmission-downloads-pvc 
    namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 460Gi
  storageClassName: local-storage  
  volumeName:  transmission-downloads-pv 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-pv 
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/hd/transmission/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: transmission-config-pvc 
    namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 2Gi
  storageClassName: local-storage  
  volumeName: transmission-config-pv 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-watch-pv 
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/hd/transmission/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: transmission-watch-pvc 
    namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 5Gi
  storageClassName: local-storage  
  volumeName: transmission-watch-pv 