apiVersion: v1
kind: Service
metadata:
  name: speedtest
  namespace: monitoring
spec:
  selector: 
    app: speedtest
  type: NodePort  
  ports:
    - port: 9798
      targetPort: 9798 
      nodePort: 32002
