---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    istio-injection: enabled
  labels:
    istio-injection: enabled
  name: default

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    istio-injection: enabled
  labels:
    istio-injection: enabled
  name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    istio-injection: enabled
  labels:
    istio-injection: enabled
  name: home

  