
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: home
spec:
  selector:
    app:  plex
  type: NodePort  
  ports:
    - port: 32469
      name: dlna-server
      targetPort: 32469 
      nodePort: 32469
    - port: 32400
      name: plex-server
      targetPort: 32400 
      nodePort: 32400
