---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-movies-pv 
spec:
  capacity:
    storage: 460Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/hd/transmission/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-movies-pvc 
    namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 460Gi
  storageClassName: local-storage  
  volumeName:   plex-movies-pv 


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv 
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/hd/plex/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-config-pvc 
    namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 2Gi
  storageClassName: local-storage  
  volumeName: plex-config-pv 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tv-pv 
spec:
  capacity:
    storage: 460Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/hd/transmission/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-tv-pvc 
    namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 460Gi
  storageClassName: local-storage  
  volumeName: plex-tv-pv 