---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: plex
  namespace: home
spec:
  scaleTargetRef:
    name: plex
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "80"
  - type: memory
    metadata:
      type: Utilization
      value: "80"