---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/volumes/prometheus-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: prometheus-pvc
    namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 150Gi
  storageClassName: local-storage  
  volumeName:  prometheus-pv
