---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Stafefulset
    name: prometheus-server
  minReplicaCount: 1
  maxReplicaCount: 1
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "90"
  - type: memory
    metadata:
      type: Utilization
      value: "90"
