name: 'Thanos - arm64'

on:
  
  push:
    branches:
      - main
    paths:
      - build/thanos/**
  
jobs:
  container:
    name: 'thanos-arm64'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: arm/thanos
        shell: bash

    steps:

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}    
   
    - name: Check Out Repo 
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: ./build/thanos
        file: ./build/thanos/Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/thanos-arm64:${{ steps.buildnumber.outputs.build_number }},${{ secrets.DOCKERHUB_USERNAME }}/thanos-arm64:latest
